udp:
  routers:
    wireguard-admin:
      entryPoints:
        - wireguard2
      service: wireguard-admin
    wireguard-client:
      entryPoints:
        - wireguard
      service: wireguard-client

  services:
    wireguard-admin:
      loadBalancer:
        servers:
          - address: wireguard.srv:51820
    wireguard-client:
      loadBalancer:
        servers:
          - address: wireguard-client.srv:51820
