http:
  routers:
    ${CTHOSTNAME}:
      entryPoints:
        - https
      service: ${CTHOSTNAME}
      rule: "Host(`${DOMAIN}`)"
      tls:
        certResolver: letsEncrypt

  services:
    ${CTHOSTNAME}:
      loadBalancer:
        servers:
          - url: https://${CTHOSTNAME}.srv/
