global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  filePath: /var/log/traefik/traefik.log
#  compress: 3
accessLog:
  filePath: /var/log/traefik/access.log
#  compress: 3

entryPoints:
  ssh:
    address: ':22'
  ssh2:
    address: ':23'
  #openvpn:
  #  address: ':1194/udp'
  #openvpn2:
  #  address: ':5555/udp'
  wireguard:
    address: ':51820/udp'
  wireguard2:
    address: ':51821/udp'
  http:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ':443'

  traefik:
    address: '${GATE_ADMIN_IPn}:8080'


api:
  dashboard: true
  insecure: true


pilot:
  dashboard: false


ping: {}


providers:
  file:
    directory: /etc/traefik.d/
    watch: true


serversTransport:
  insecureSkipVerify: true



certificatesResolvers:
  letsEncrypt:
    acme:
      email: '${EMAIL}'
      storage: '/etc/traefik/acme.json'
      tlsChallenge: {}
