http:
  routers:
    nextcloud:
      entryPoints:
        - https
      service: nextcloud
      rule: "Host(`${DOMAIN}`)"
      tls:
        certResolver: letsEncrypt

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: https://nextcloud.srv/
