tcp:
  routers:
    ${CTHOSTNAME}:
      entryPoints:
        - ${CTHOSTNAME}
      service: ${CTHOSTNAME}
      rule: "HostSNI(`*`)"

  services:
    ${CTHOSTNAME}:
      loadBalancer:
        servers:
          - address: ${CTHOSTNAME}.srv:5555
